#PR-5

name: Build and upload wheels

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.21.0
        continue-on-error: ${{ matrix.os == 'windows-latest' }}
        with:
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v4
        if: matrix.os != 'windows-latest'
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl